version: '2'

services:
  redis:
    image: redis:latest
    ports:
      - "6379"

  hitcounter:
    build: .
    image: hitcounter
    ports:
      - "5000"
    environment:
      - REDIS_HOST=redis
    labels:
      kompose.service.type: LoadBalancer
