apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    io.kompose.service: hitcounter
  name: hitcounter
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: hitcounter
  type: LoadBalancer
status:
  loadBalancer: {}
